### ISSUE TITLE
you can now use windows-rs instead of winapi

### ISSUE THREAD

**Issue by Kreijstal** [recombinant/PetzoldPW5e-rs#3]
it should probably contain things you are looking for

**Comment by recombinant** [comment]
The idea of PetzoldPW5e-rs was to use winapi as per the book. Yes, windows-rs is an alternative. I did make two small commits to windows-rs, one in 2015 and another in 2018. At the time both Rust and windows-rs presented (slowly) moving targets and it was simpler to only need to keep this project up to date with just Rust. Today (late 2024) there is negligible traffic on this repository and I don't need to advertise my stale Rust skills. Someone else can can create a windows-rs version of Charles Petzold's work - all 2.4kg of book,
